### ISSUE TITLE
Empty inbound_mapping on a LOCAL_IDENTITY_MAPPING type causes a validation error

### ISSUE THREAD

**Issue by sailorgallifrey** [iwarapter/terraform-provider-pingfederate#104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.15.0

### Affected Resource(s)

* pingfederate_authentication_polocies

### Terraform Configuration Files

```hcl
children {
        action {
          context = "Registration"
          type    = "LOCAL_IDENTITY_MAPPING"
          inbound_mapping {
          }
         }
}
```

### Expected Behavior

It is valid to have no inbound mapping on the contract fulfillment for a Local Identity Profile within an authentication policy. Terraform should not throw an error or should not show a diff when the `inbound_mapping` is excluded.

### Actual Behavior

When importing authentication policies into state and running a terraform plan an empty `inbound_mapping` is shown as being removed if there is no inbound_mapping in the TF file. If you add the empty `inbound_mapping` to the tf file on the appropriate child section terraform then throws an error when you run `terraform plan`.

### Steps to Reproduce

1. Create a policy in Ping Federate with a Registration step linking to a Local Identity Profile and do not set any inbound mappings within the Inbound Identity Mapping contract fulfillment
2. Import auth policies into tf state
3. Comment out the policy resource and run `terraform plan` to get the structure
4. UnComment and copy the output from plan reformatting as necessary and removing generated properties (This will include an empty `inbound_mapping` object on the Local Identity Profile step
5. Run `terraform plan` again (Terraform will show a validation error that indicates that `inbound_mapping` requires an `attribute_contract_fulfillment`

```
╷
│ Error: Missing required argument
│ 
│   on authentication-policies.tf line 171, in resource "pingfederate_authentication_policies" "authentication_policies":
│  171:           inbound_mapping {
│ 
│ The argument "authn_selection_trees.1.root_node.0.children.1.action.0.inbound_mapping.0.attribute_contract_fulfillment" is required, but no definition was found.
```

### References

* #0000

**Comment by iwarapter** [comment]
What version of pingfederate & provider are you using?

**Comment by iwarapter** [comment]
Hi @sailorgallifrey i haven't been able to reproduce this, do you have a TF reproducer or pf data.zip which can show this?

**Comment by iwarapter** [comment]
Hi @sailorgallifrey were you able to solve this?
