### ISSUE TITLE
TEXT not accepted as valid type in AttributeContractFulfillment

### ISSUE THREAD

**Issue by mosersil** [iwarapter/terraform-provider-pingfederate#129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
For AttributeFulfillment, the source type "TEXT" is not accepted by the latest version of the provider. The API documentation of PF is a bit misleading, as there is obviously a missing line break :)
![image](https://user-images.githubusercontent.com/15806704/131872425-520ee7e7-f629-4a5b-8fdc-c8720049dd82.png)

### Affected Resource(s)

* pingfederate_idp_adapter

### Terraform Configuration Files

```hcl
(...)
attribute_mapping {
  attribute_contract_fulfillment {
     key_name = "foo"
     value = "bar"
     source {
        type = "TEXT"
     }
}
(...)
```

### Expected Behavior

For attribute_contract_fulfillment, source type "TEXT" should be accepted

### Actual Behavior

Validation error occures

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by iwarapter** [comment]
fix merged to master - will be in next release
