### ISSUE TITLE
Issuance Criteria applying ordering. 

### ISSUE THREAD

**Issue by ashhammond** [iwarapter/terraform-provider-pingfederate#137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* pingfederate_XXXXX

All `issuance_criteria` based resources 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here
```

### Debug Output

```hcl



                                  ~ issuance_criteria {
                                      ~ conditional_criteria {
                                            ~ value          = "user1" -> "user2"
                                            # (2 unchanged attributes hidden)

                                            # (1 unchanged block hidden)
                                        }
                                      ~ conditional_criteria {
                                          ~ value          = "user2" -> "user1"
                                            # (2 unchanged attributes hidden)

                                            # (1 unchanged block hidden)
                                        }
                                        # (5 unchanged blocks hidden)
                                    }

                                    # (2 unchanged blocks hidden)
                                }



```

### Expected Behavior

The provider should not enforce ordering. 

### Actual Behavior

PingFederate resources have a section called `issuance criteria`, this allowed conditions to be met or not met, to decide if some thing should happen, i.e. allow a user to authenticate. 

The provider is applying ordering to this data, which is not available in the UI and API.  

### Steps to Reproduce

1. Create the following issuance criteria:

```hcl

issuance_criteria {
          
                      conditional_criteria {
                        attribute_name = "username"
                        condition      = "EQUALS_CASE_INSENSITIVE"
                        value          = "user1"
                        source {
                          id   = pingfederate_idp_adapter.form_adapt.id
                          type = "ADAPTER"
                        }
                      }
                      conditional_criteria {
                        attribute_name = "username"
                        condition      = "EQUALS_CASE_INSENSITIVE"
                        value          = "user2
                        source {
                          id   = pingfederate_idp_adapter.form_adapt.id
                          type = "ADAPTER"
                        }
                      }
 }

```

2. `terraform apply`
3. Switch `user1` and `user2` ordering. 
4. `terraform plan`
5. plan is non empty 
### References

* #0000

**Comment by iwarapter** [comment]
Both the UI and the API respect the ordering of the issuance criteria (although the UI doesn't allow you to change it, api changes are reflected). Because the API honours this, the provider will too.
