### ISSUE TITLE
Authentication Policy: Attribute rules not working

### ISSUE THREAD

**Issue by mosersil** [iwarapter/terraform-provider-pingfederate#148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.14.10

### Affected Resource(s)

* pingfederate_authentication_policies

### Terraform Configuration Files

```hcl
resource "pingfederate_authentication_policies" "sample" {
  fail_if_no_selection = false
  authn_selection_trees {
    name = "MySamplePolicy"
    root_node {
       action {
          type = "AUTHN_SOURCE"
          context = "Yes"
          authentication_source {
            type = "IDP_ADAPTER"
            source_ref {
              id = pingfederate_idp_adapter.idfirstadapter.id
            }
          }
          attribute_rules {
            items {
              attribute_name = "pwdReset"
              condition = "EQUALS_CASE_INSENSITIVE"
              expected_value = "TRUE"
              result = "CHANGE_PW"
            }
          }
        }
        children {
          action {
            type = "DONE"
            context = "Fail"
          }
        }
        children {
          action {
            context = "CHANGE_PW"
            type = "AUTHN_SOURCE"
            authentication_source {
              type = "IDP_ADAPTER"
              source_ref {
                id = pingfederate_idp_adapter.somealternativeadapter.id
              }
            }
            input_user_id_mapping {
              value = "subject"
              source {
                id = pingfederate_idp_adapter.idfirstadapter.id
                type = "ADAPTER"
              }
            }
          }
          children {
            action {
              type = "DONE"
              context = "Fail"
            }
          }
(...)
```

### Expected Behavior
Scenario: I have an identifier first adapter, allowing the user to enter a userId. Depending on the state of this account, the login journey will be different.

When defining a rule on an adapter, I expect that I can refer to the outcome of this rule in the context in a child element. This was working in older version (e.g. 0.0.14)

### Actual Behavior
`Error: unable to update AuthenticationPolicies: Validation error(s) occurred. Please review the error(s) and address accordingly.
The child context 'CHANGE_PW' is invalid for this type of action. Valid options are: an attribute rule result value, Fail, Success.`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by iwarapter** [comment]
@mosersil do you have a complete reproducer you can share for this? Which version of PingFederate is this running against?

**Comment by mosersil** [comment]
Finally... 
https://github.com/mosersil/terraform-provider-pingfederate/tree/reproduce_attribute_rule_issue
PF version I am using is 10.3.1.0

**Comment by iwarapter** [comment]
hey i have a fix in for this, unfortunately PingIdentity have changed/broken a few of the containers I use in testing so its going to take me awhile to fix that and get a release out.
