### ISSUE TITLE
SP Connection with WS-Trust apply fails with "Abort Path field is not required"

### ISSUE THREAD

**Issue by awalmsley** [iwarapter/terraform-provider-pingfederate#158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
$ terraform -v
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/iwarapter/pingfederate v0.0.23
```
### Affected Resource(s)
* pingfederate_idp_sp_connection

### Terraform Configuration Files

```hcl
resource "pingfederate_idp_sp_connection" "this" {
  active    = true
  base_url  = "https://some.url"
  entity_id = "requestcontractissue"
  name      = "requestcontractissue"
  type      = "SP"

  credentials {
    signing_settings {
      signing_key_pair_ref {
        id = "xgr9wy6t83v7morfeaaz4pg9b"
      }
    }
  }

  ws_trust {
    default_token_type = "SAML20"
    minutes_after      = 60
    minutes_before     = 5
    partner_service_ids = [
      "https://some.url"
    ]

    attribute_contract {
      core_attributes {
        name      = "TOKEN_SUBJECT"
        namespace = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
      }
    }

    # request_contract_ref {
    #   id = "stsassumerole"
    # }

    token_processor_mappings {

      attribute_contract_fulfillment {
        key_name = "TOKEN_SUBJECT"
        value    = "null"

        source {
          type = "TEXT"
        }
      }

      idp_token_processor_ref {
        id = "UsernameTokenProcessor"
      }
    }
  }
}
```

### Expected Behavior

SP Connection should be created.

### Actual Behavior

```bash
pingfederate_idp_sp_connection.this: Creating...
╷
│ Error: unable to create IdpSpConnections: Validation error(s) occurred. Please review the error(s) and address accordingly.
│ The Abort Path field is not required.
│ 
│   with pingfederate_idp_sp_connection.this,
│   on idp_sp_connection.tf line 1, in resource "pingfederate_idp_sp_connection" "this":
│    1: resource "pingfederate_idp_sp_connection" "this" {
│ 
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Works when a request_contract_ref included

### References
https://github.com/iwarapter/terraform-provider-pingfederate/issues/155

* #0000

**Comment by iwarapter** [comment]
Which version of PingFederate is this against?

**Comment by awalmsley** [comment]
From the admin console, PRODUCT VERSION: 10.2

**Comment by awalmsley** [comment]
From the Admin API
{
    "version": "10.1.2.0"
}

**Comment by awalmsley** [comment]
Test against PingFederate v10.3.1.0 also, got the same result.

**Comment by iwarapter** [comment]
Thanks for this - i tested against 10.2.7 and was able to reproduce, there is a bug in the way ping is handling certain features being enabled for the `ws_trust` settings and how terraform defaults certain fields. The next version fixes this.

**Comment by awalmsley** [comment]
Thank you very much, will try it out when available.
