### ISSUE TITLE
OAuth client creation loops rather than detecting a duplication. 

### ISSUE THREAD

**Issue by ashhammond** [iwarapter/terraform-provider-pingfederate#165]
Hello. 

The following has been noticed. If the provider tries to create a duplicate OAuth client, the PF Admin API responds correctly stating and error due to being a duplicate.  The provider does not honer the response and attempts to recreate it N times. Eventually the provider honers the response and returns the correct message and exits, 

Is there a reason the provider does not honer the first reply suggesting a duplicate and exit then?  Granted the initial source that creates this situation is bad configuration.   

We are querying the delay. Is there a reason? 

Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Gitter](https://gitter.im/iwarapter/terraform-provider-pingfederate)
* [HashiCorp Community Forum](https://discuss.hashicorp.com/c/terraform-providers)

**Comment by iwarapter** [comment]
Yeah this is a legacy workaround from the race condition found in the PF certificates API, it'll be removed in the next release.
