### ISSUE TITLE
Support for Redirect Validation Settings

### ISSUE THREAD

**Issue by sansub** [iwarapter/terraform-provider-pingfederate#193]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please could the provider support PingFederate Redirect Validation

### New or Affected Resource(s)

* pingfederate_redirect_validation_settings

### Potential Terraform Configuration

```hcl
resource "pingfederate_redirect_validation_settings" "settings" {
  whitelist_domain {
      valid_domain              = ""
      valid_path                = ""
      allow_query_and_fragment  = false
      require_https             = true
      target_resource_slo       = true
      idp_discovery             = false
      in_error_resource         = true
      target_resource_sso       = true
  }

  enable_target_resource_validation_for_sso           = true
  enable_target_resource_validation_for_slo           = true
  enable_target_resource_validation_for_idp_discovery = true
  enable_inerror_resource_validation                  = true
  enable_wreply_validation_slo                        = true
  
}
```

### References

* #0000

**Comment by iwarapter** [comment]
fixed with https://github.com/iwarapter/terraform-provider-pingfederate/releases/tag/v0.1.0
