### ISSUE TITLE
Bug - cannot create pingfederate_authentication_policy_contract or pingfederate_oauth_client resources

### ISSUE THREAD

**Issue by ParadigmZero** [iwarapter/terraform-provider-pingfederate#245]
# Bug: #

Cannot create `pingfederate_authentication_policy_contract` or `pingfederate_oauth_client` resources due to bug in provider.

## Affected resources: #

pingfederate_authentication_policy_contract
pingfederate_oauth_client

## Setup: ##

Provider version:
0.1.0 ( latest when posting this )

Terraform version:
1.2.5

PingFederate version:
11.1.1-edge

## Steps to Reproduce: ##

Try creating a `pingfederate_authentication_policy_contract` and/or `pingfederate_oauth_client` resource. For instance:

```
resource "pingfederate_authentication_policy_contract" "test" {
  name = "test"
}

resource "pingfederate_oauth_client" "example" {
  client_id   = "example"
  name        = "example"
  grant_types = ["CLIENT_CREDENTIALS"]

  client_auth = {
    secret = "super_top_secret"
    type   = "SECRET"
  }
}
```

## Error output (actual behavior): ##

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to pingfederate_oauth_client.example, provider "provider[\"registry.terraform.io/iwarapter/pingfederate\"]" produced an unexpected new value:
│ .oidc_policy: was null, but now cty.ObjectVal(map[string]cty.Value{"grant_access_session_revocation_api":cty.False,
│ "grant_access_session_session_management_api":cty.False, "id_token_content_encryption_algorithm":cty.NullVal(cty.String),
│ "id_token_encryption_algorithm":cty.NullVal(cty.String), "id_token_signing_algorithm":cty.NullVal(cty.String), "logout_uris":cty.NullVal(cty.List(cty.String)),
│ "pairwise_identifier_user_type":cty.False, "ping_access_logout_capable":cty.False, "policy_group":cty.NullVal(cty.String),
│ "sector_identifier_uri":cty.NullVal(cty.String)}).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to pingfederate_authentication_policy_contract.test, provider "provider[\"registry.terraform.io/iwarapter/pingfederate\"]" produced an
│ unexpected new value: .extended_attributes: was null, but now cty.SetValEmpty(cty.String).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by iwarapter** [comment]
Thanks for raising this, this actually lead to an issue in the underlying terraform plugin framework, which I'm waiting on.

**Comment by ParadigmZero** [comment]
@iwarapter  just having an initial look at what you linked, I see terraform-plugin-framework has closed that issue that was raised. I am wondering, is this a case of now waiting for your next provider version to fix this? Thanks.

**Comment by iwarapter** [comment]
hi @ParadigmZero, whilst fixing the default values for the `oidc_policy` I came across another core bug - https://github.com/hashicorp/terraform-plugin-framework/issues/599 which needs resolving to fix the issue with the `oidc_policy` attributes
