### ISSUE TITLE
pingfederate_oauth_access_token_manager plugin_descriptor_ref for JWT Bearer Token

### ISSUE THREAD

**Issue by Vasista-Eranki** [iwarapter/terraform-provider-pingfederate#267]
Hi

I'm trying to provision an OAuth Access Token Manager in PingFederate. The Plugin descriptor ref. id is set as: "com.pingidentity.pf.access.token.management.plugins.JwtBearerAccessTokenManagementPlugin". 

![image](https://user-images.githubusercontent.com/60959482/222441837-7d0252f1-bc70-4027-adc8-60de1053265b.png)

However, this value is not accepted due to string length limits; 
![image](https://user-images.githubusercontent.com/60959482/222442607-c2ccc240-3b7b-4768-8d7c-159c97ea01f1.png)

``` terraform
│ Error: unable to create OauthAccessTokenManagers: Validation error(s) occurred. Please review the error(s) and address accordingly.
│ The plugin ID must be less than 33 characters, contain no spaces, and be alphanumeric.
│
│   with pingfederate_oauth_access_token_manager.oauth_access_token_mgr,
│   on main.tf line 49, in resource "pingfederate_oauth_access_token_manager" "oauth_access_token_mgr":
│   49: resource "pingfederate_oauth_access_token_manager" "oauth_access_token_mgr" {
```

Can you please suggest a way to proceed with this.

**Comment by iwarapter** [comment]
its the `_` in the name, its not alphanumeric

**Comment by Vasista-Eranki** [comment]
> its the `_` in the name, its not alphanumeric

it worked. Thank you..
