### ISSUE TITLE
data "pingfederate_oauth_auth_server_settings"  "" {}

### ISSUE THREAD

**Issue by Vasista-Eranki** [iwarapter/terraform-provider-pingfederate#269]
Hi

We're using this module to provision on a Ping Federate 11.2 environment. Our requirement is as follows:

Based on the inputs, we may have to add/delete/update the urls in the CORS policy of authorization server via the pingfederate_oauth_auth_server_settings.allowed_origins.. Since, the data addition shall be relative, we require a data-resource for pingfederate_oauth_auth_server_settings so as to read the existing list of allowed_origins and append/remove the new change we're about to make. We see that this data resource seemed missing and hence is this request to include it.

Could you include a data resource in compliance with the pingfederate_oauth_auth_server_settings, so as we can just read the existing auth. server settings. _Alternatively, a custom resource only to manage the allowed_origins would also work._

**Comment by iwarapter** [comment]
This has been released in v0.2.0
