### ISSUE TITLE
Metadata URL resource

### ISSUE THREAD

**Issue by ashhammond** [iwarapter/terraform-provider-pingfederate#277]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Pingfederate has the ability to consume metadata endpoints for SAML providers and these can then be associate to a specific SAML connection inside PingFederate 

### New or Affected Resource(s)

* pingfederate_metadata_url

### Potential Terraform Configuration

```hcl
resource "pingfederate_metadata_url" "example_metadata_url" {
  name = "example_organisation"
  url  = "https://example.com/FederationMetadata.xml"
  x509_file {
    file_data = file("example.pem")
  }
  validateSignature = true
}
```

### References

`pf-admin-api/v1/metadataUrls`

**Comment by iwarapter** [comment]
This has been released in v0.2.0
