### ISSUE TITLE
Ping Federate 10 - Change in default values for oauth server settings

### ISSUE THREAD

**Issue by RalphBragg** [iwarapter/terraform-provider-pingfederate#42]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.28
+ provider.pingaccess v0.7.0
+ provider.pingfederate v0.0.8

### Affected Resource(s)

# pingfederate_oauth_auth_server_settings.settings will be updated in-place
  ~ resource "pingfederate_oauth_auth_server_settings"
      

### Terraform Configuration Files

```hcl
resource "pingfederate_oauth_auth_server_settings" "settings" {

  scopes {
    name        = "openid"
    description = "openid"
  }
  scopes {
    name        = "profile"
    description = "profile"
  }
  scopes {
    name        = "email"
    description = "email"
  }
  scopes {
    name        = "address"
    description = "address"
  }
  scopes {
    name        = "phone"
    description = "phone"
  }
  scopes {
    name        = "email"
    description = "email"
  }
  scopes {
    name        = "idp"
    description = "idp"
  }

  exclusive_scopes {
    description = "Account Number"
    name        = "acc_no"
  }

  default_scope_description      = ""
  authorization_code_timeout     = 60
  authorization_code_entropy     = 30
  refresh_token_length           = 42
  refresh_rolling_interval       = 0
  persistent_grant_lifetime      = -1
  persistent_grant_lifetime_unit = "DAYS"
}
```

### Expected Behavior

The defaults of unspecified values shouldn't cause an exception.

### Actual Behavior

The provider tried to set invalid attribute values for the default and failed to apply

### Steps to Reproduce

Create a resource  pingfederate_oauth_auth_server_settings
Do not specify 

      - persistent_grant_lifetime                  = -1 -> null
      - persistent_grant_lifetime_unit             = "DAYS" -> 
      
And try and apply. 

### References

* #0000

**Comment by iwarapter** [comment]
Fixed in v0.0.9
