### ISSUE TITLE
Support for oauth openid static keys endpoint 

### ISSUE THREAD

**Issue by ashraidiam** [iwarapter/terraform-provider-pingfederate#86]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If the provider could support enabling and disabling of staticJwksEnabled 
/pf-admin-api/v1/keyPairs/oauthOpenIdConnect

### New or Affected Resource(s)

* pingfederate_9.x >
suggested ```pingfederate_keypairs_oauth_openid_connect```

### Potential Terraform Configuration

```hcl
resource "pingfederate_keypairs_oauth_openid_connect" "static_key" {

  staticJwksEnabled = true
  
}
```

**Comment by RalphBragg** [comment]
I think this would be a very good resource to be included.
