### ISSUE TITLE
adding entries to an exisiting pingfederate_authentication_selector

### ISSUE THREAD

**Issue by xbalajipge** [iwarapter/terraform-provider-pingfederate#93]
How can we one add a new entry to an existing pingfederate_authentication_selector without importing? I'm trying to create a new SP connection and the same to the pingfederate_authentication_selector. At this time, unless the existing pingfederate_authentication_selector is imported, I'm unable to add it, which makes the process manual, is there any other solution. Thanks!

**Comment by iwarapter** [comment]
Just to be clear, you have a manually created authentication selector already in PingFederate that you want to then manage with terraform? If so you would need to import the resource as terraform can only manage resources it knows about (or creates to begin with).

**Comment by xbalajipge** [comment]
@iwarapter , thanks for your response. Typically, we don't create authentication selector with SP connection; but add entries to an existing authentication selector. Would like to know if there something like **_pingfederate_authentication_selector_item_** similar to **aws_dynamodb_table_item**.   This will be much helpful since we wouldn't need to do an import in that case.

**Comment by xbalajipge** [comment]
@iwarapter , thank you. I'm using **com.pingidentity.pf.selectors.connectionset.ConnectionSetAdapterSelector** and want to add the newly created SP connection (**resource "pingfederate_idp_sp_connection"**) as an additional entry to the ```table``` of ```rows``` already there. If this is not the right way of adding an SP connector do let me know, I'm just trying to see if I can do this without manual intervention. Thanks.

**Comment by iwarapter** [comment]
You need to import the original selector, then add a new row for the new connection.

**Comment by xbalajipge** [comment]
@iwarapter  thank you. This will need manual intervention, let me know if you have any suggestions to automate the import and adding an entry that will be helpful. I'll close this case if there is no other option.

**Comment by xbalajipge** [comment]
Thanks @iwarapter  for the timely and quick responses.
