### ISSUE TITLE
OIDC connect policy computed core attributes. 

### ISSUE THREAD

**Issue by ashraidiam** [iwarapter/terraform-provider-pingfederate#94]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.5

### Affected Resource(s)

* pingfederate_10.x has been used here. 

When using a `pingfederate_oauth_openid_connect_policy` if only core attributes are used, an empty `attribute_contract` block must be supplied. If this block is not supplied, the provider will loop over the attributes wanting to remove subject/sub resulting in a configuration that never completes.  

### Terraform Configuration Files

```hcl
resource "pingfederate_oauth_openid_connect_policy" "oidc_cheese_policy" {
  name                      = "cheesePolicy"
  policy_id                 = "cheesePolicy"
  include_sri_in_id_token   = false
  include_user_in_id_token  = false
  include_shash_in_id_token = false

  access_token_manager_ref {
    id = pingfederate_oauth_access_token_manager.cheese.id
  }
  attribute_contract {

  }
  attribute_mapping {
    attribute_contract_fulfillment {
      key_name = "sub"
      source {
        type = "TOKEN"
      }
      value = "subject"
    }
  }
}
```

### Debug Output

```hcl
      - attribute_contract {
          - core_attributes {
              - include_in_id_token       = false -> null
              - include_in_user_info      = false -> null
              - name                      = "sub" -> null
              - override_default_delivery = false -> null
            }
        }
```

### Expected Behavior

The resource is created and core attributes come from the computed list. 

### Actual Behavior

If this block is not supplied, the provider will loop over the attributes wanting to remove subject/sub resulting in a configuration that never completes.  

### Steps to Reproduce

```hcl
resource "pingfederate_oauth_openid_connect_policy" "oidc_cheese_policy" {
  name                      = "cheesePolicy"
  policy_id                 = "cheesePolicy"
  include_sri_in_id_token   = false
  include_user_in_id_token  = false
  include_shash_in_id_token = false

  access_token_manager_ref {
    id = pingfederate_oauth_access_token_manager.cheese.id
  }
  attribute_mapping {
    attribute_contract_fulfillment {
      key_name = "sub"
      source {
        type = "TOKEN"
      }
      value = "subject"
    }
  }
}
```

**Comment by RalphBragg** [comment]
Definitely a major issue.
